-- OMS initial schema draft for review.
-- Target: MySQL first draft.
-- This file is not wired to Flyway/Liquibase yet.
-- PostgreSQL notes:
--   - BIGINT AUTO_INCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   - DATETIME(6) -> TIMESTAMPTZ
--   - JSON -> JSONB
--   - Partial indexes can be considered later for active master rows and unresolved validation errors.
-- Master policy:
--   - The 1st MVP uses tenant-scoped current master rows.
--   - Master uploads upsert current rows and keep file-level summary history.
--   - This draft does not create heavy master version/history snapshot tables.

CREATE TABLE tenants (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_tenants_code UNIQUE (code)
);

CREATE TABLE clients (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_clients_tenant_code UNIQUE (tenant_id, code),
  CONSTRAINT fk_clients_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_scope_type VARCHAR(16) NOT NULL,
  tenant_id BIGINT NULL,
  client_id BIGINT NULL,
  login_id VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NULL,
  password_hash VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  last_login_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_users_login_id UNIQUE (login_id),
  CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_users_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE roles (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE api_keys (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NULL,
  name VARCHAR(100) NOT NULL,
  key_hash VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  allowed_scope JSON NULL,
  expires_at DATETIME(6) NULL,
  last_used_at DATETIME(6) NULL,
  created_by BIGINT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_api_keys_tenant_hash UNIQUE (tenant_id, key_hash),
  CONSTRAINT fk_api_keys_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_api_keys_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_api_keys_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE master_upload_batches (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  master_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  stored_path VARCHAR(1000) NULL,
  file_hash VARCHAR(128) NULL,
  file_size BIGINT NULL,
  content_type VARCHAR(255) NULL,
  row_count INT NOT NULL DEFAULT 0,
  inserted_count INT NOT NULL DEFAULT 0,
  updated_count INT NOT NULL DEFAULT 0,
  unchanged_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  uploaded_by BIGINT NULL,
  uploaded_at DATETIME(6) NOT NULL,
  applied_at DATETIME(6) NULL,
  request_id VARCHAR(100) NULL,
  message VARCHAR(1000) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_master_upload_batches_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_master_upload_batches_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE product_master_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  ezadmin_code VARCHAR(64) NOT NULL,
  product_name VARCHAR(255) NULL,
  customer_product_code VARCHAR(64) NULL,
  box_qty DECIMAL(18,3) NULL,
  outbound_unit VARCHAR(64) NULL,
  temperature_type VARCHAR(64) NULL,
  cbm DECIMAL(18,6) NULL,
  active_yn BOOLEAN NOT NULL DEFAULT TRUE,
  last_master_upload_batch_id BIGINT NULL,
  row_no INT NULL,
  raw_row_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_product_master_items_code UNIQUE (tenant_id, ezadmin_code),
  CONSTRAINT fk_product_master_items_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_product_master_items_last_upload FOREIGN KEY (last_master_upload_batch_id) REFERENCES master_upload_batches(id)
);

CREATE TABLE store_route_master_items (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  baljugo_code VARCHAR(64) NOT NULL,
  customer_code VARCHAR(64) NULL,
  brand_name VARCHAR(255) NULL,
  store_name VARCHAR(255) NULL,
  area VARCHAR(100) NULL,
  delivery_day VARCHAR(32) NULL,
  delivery_round VARCHAR(64) NULL,
  vehicle_name VARCHAR(255) NULL,
  driver_name VARCHAR(255) NULL,
  address VARCHAR(500) NULL,
  active_yn BOOLEAN NOT NULL DEFAULT TRUE,
  last_master_upload_batch_id BIGINT NULL,
  row_no INT NULL,
  raw_row_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_store_route_master_items_code UNIQUE (tenant_id, baljugo_code),
  CONSTRAINT fk_store_route_master_items_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_store_route_master_items_last_upload FOREIGN KEY (last_master_upload_batch_id) REFERENCES master_upload_batches(id)
);

CREATE TABLE upload_batches (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_no VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  delivery_date DATE NULL,
  product_master_checked_at DATETIME(6) NULL,
  store_route_master_checked_at DATETIME(6) NULL,
  uploaded_by BIGINT NULL,
  uploaded_at DATETIME(6) NOT NULL,
  validated_at DATETIME(6) NULL,
  confirmed_at DATETIME(6) NULL,
  cancelled_at DATETIME(6) NULL,
  rolled_back_at DATETIME(6) NULL,
  confirmed_by BIGINT NULL,
  error_count INT NOT NULL DEFAULT 0,
  warning_count INT NOT NULL DEFAULT 0,
  info_count INT NOT NULL DEFAULT 0,
  memo VARCHAR(1000) NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_upload_batches_batch_no UNIQUE (tenant_id, client_id, batch_no),
  CONSTRAINT fk_upload_batches_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_upload_batches_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_upload_batches_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id),
  CONSTRAINT fk_upload_batches_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users(id)
);

CREATE TABLE uploaded_files (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  file_type VARCHAR(32) NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  stored_path VARCHAR(1000) NOT NULL,
  file_hash VARCHAR(128) NOT NULL,
  file_size BIGINT NOT NULL,
  content_type VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_uploaded_files_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_uploaded_files_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_uploaded_files_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id),
  CONSTRAINT fk_uploaded_files_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE excel_sheet_results (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(255) NOT NULL,
  sheet_type VARCHAR(32) NOT NULL,
  suffix_value VARCHAR(100) NULL,
  header_row_no INT NULL,
  data_row_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(1000) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_excel_sheet_results_batch_sheet UNIQUE (batch_id, sheet_name),
  CONSTRAINT fk_excel_sheet_results_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_excel_sheet_results_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_excel_sheet_results_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id)
);

CREATE TABLE scan_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(255) NOT NULL,
  scan_center VARCHAR(100) NULL,
  delivery_date DATE NULL,
  bus VARCHAR(100) NULL,
  barcode VARCHAR(128) NULL,
  order_business_site_code VARCHAR(64) NULL,
  store_name VARCHAR(255) NULL,
  product_code VARCHAR(64) NULL,
  product_name VARCHAR(255) NULL,
  label_qty DECIMAL(18,3) NULL,
  unit VARCHAR(32) NULL,
  box_sequence VARCHAR(64) NULL,
  temperature_type VARCHAR(64) NULL,
  row_no INT NOT NULL,
  raw_row_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_scan_lines_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_scan_lines_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_scan_lines_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id)
);

CREATE TABLE pl_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(255) NOT NULL,
  pl_type VARCHAR(16) NOT NULL,
  order_no VARCHAR(64) NULL,
  store_code VARCHAR(64) NULL,
  store_name VARCHAR(255) NULL,
  brand_name VARCHAR(255) NULL,
  product_code VARCHAR(64) NULL,
  product_name VARCHAR(255) NULL,
  unit VARCHAR(64) NULL,
  storage_temperature VARCHAR(64) NULL,
  due_date DATE NULL,
  order_qty DECIMAL(18,3) NULL,
  vehicle_name VARCHAR(255) NULL,
  cbm DECIMAL(18,6) NULL,
  qr_code VARCHAR(255) NULL,
  box_qty DECIMAL(18,3) NULL,
  row_no INT NOT NULL,
  raw_row_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_pl_lines_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_pl_lines_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_pl_lines_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id)
);

CREATE TABLE label_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(255) NOT NULL,
  label_type VARCHAR(16) NOT NULL,
  order_no VARCHAR(64) NULL,
  store_code VARCHAR(64) NULL,
  store_name VARCHAR(255) NULL,
  product_code VARCHAR(64) NULL,
  product_name VARCHAR(255) NULL,
  order_qty DECIMAL(18,3) NULL,
  sequence_no VARCHAR(64) NULL,
  matching_code VARCHAR(128) NULL,
  qr_code VARCHAR(255) NULL,
  box_sequence VARCHAR(64) NULL,
  total_box_qty DECIMAL(18,3) NULL,
  row_no INT NOT NULL,
  raw_row_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_label_lines_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_label_lines_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_label_lines_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id)
);

CREATE TABLE order_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  source_pl_line_id BIGINT NOT NULL,
  order_no VARCHAR(64) NULL,
  store_code VARCHAR(64) NULL,
  store_name VARCHAR(255) NULL,
  brand_name VARCHAR(255) NULL,
  product_code VARCHAR(64) NULL,
  product_name VARCHAR(255) NULL,
  unit VARCHAR(64) NULL,
  order_qty DECIMAL(18,3) NULL,
  due_date DATE NULL,
  vehicle_name VARCHAR(255) NULL,
  delivery_round VARCHAR(64) NULL,
  area VARCHAR(100) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_order_lines_source_pl UNIQUE (source_pl_line_id),
  CONSTRAINT fk_order_lines_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_order_lines_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_order_lines_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id),
  CONSTRAINT fk_order_lines_source_pl FOREIGN KEY (source_pl_line_id) REFERENCES pl_lines(id)
);

CREATE TABLE validation_errors (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  severity VARCHAR(16) NOT NULL,
  error_code VARCHAR(64) NOT NULL,
  domain VARCHAR(32) NOT NULL,
  sheet_name VARCHAR(255) NULL,
  row_no INT NULL,
  column_name VARCHAR(255) NULL,
  line_table VARCHAR(64) NULL,
  line_id BIGINT NULL,
  message TEXT NOT NULL,
  original_value TEXT NULL,
  normalized_value TEXT NULL,
  resolved_yn BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_validation_errors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_validation_errors_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_validation_errors_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id)
);

CREATE TABLE batch_audit_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NULL,
  action VARCHAR(64) NOT NULL,
  before_status VARCHAR(32) NULL,
  after_status VARCHAR(32) NULL,
  actor_id BIGINT NULL,
  request_id VARCHAR(100) NULL,
  message TEXT NULL,
  metadata_json JSON NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_batch_audit_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_batch_audit_logs_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_batch_audit_logs_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id),
  CONSTRAINT fk_batch_audit_logs_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE TABLE api_call_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  api_key_id BIGINT NULL,
  request_id VARCHAR(100) NULL,
  path VARCHAR(500) NOT NULL,
  method VARCHAR(16) NOT NULL,
  query_string TEXT NULL,
  response_status INT NOT NULL,
  response_time_ms INT NULL,
  client_ip VARCHAR(64) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_api_call_logs_request_id UNIQUE (request_id),
  CONSTRAINT fk_api_call_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_api_call_logs_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_api_call_logs_api_key FOREIGN KEY (api_key_id) REFERENCES api_keys(id)
);

CREATE TABLE download_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  batch_id BIGINT NULL,
  download_type VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  filter_json JSON NULL,
  row_count INT NULL,
  downloaded_by BIGINT NULL,
  request_id VARCHAR(100) NULL,
  downloaded_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_download_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_download_logs_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_download_logs_batch FOREIGN KEY (batch_id) REFERENCES upload_batches(id),
  CONSTRAINT fk_download_logs_user FOREIGN KEY (downloaded_by) REFERENCES users(id)
);

-- Enum policy:
-- batch_status: UPLOADED, VALIDATING, VALIDATION_FAILED, READY_TO_CONFIRM, CONFIRMED, CANCELLED, ROLLED_BACK
-- pl_type: EA, BOX
-- label_type: EA, BOX
-- validation_severity: ERROR, WARNING, INFO
-- upload_domain: SCAN, PL, LABEL, ORDER, MASTER
-- sheet_type: SCAN_UPLOAD, PL_EA, PL_BOX, LABEL_EA, LABEL_BOX, IGNORED, UNKNOWN
-- master_type: PRODUCT, STORE_ROUTE
-- master_upload_status: UPLOADED, PROCESSING, APPLIED, PARTIAL_FAILED, FAILED
-- user_scope_type: SYSTEM, TENANT, CLIENT
-- user_scope_type policy:
--   SYSTEM: tenant_id NULL, client_id NULL
--   TENANT: tenant_id NOT NULL, client_id NULL
--   CLIENT: tenant_id NOT NULL, client_id NOT NULL
--   Scope-specific required values are enforced by application validation in the 1st MVP.
-- MySQL 8.0.16+ CHECK constraints can be added after version confirmation.

CREATE INDEX idx_clients_tenant_status ON clients (tenant_id, status);
CREATE INDEX idx_users_scope_status ON users (user_scope_type, status);
CREATE INDEX idx_users_tenant_status ON users (tenant_id, status);
CREATE INDEX idx_users_client_status ON users (client_id, status);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_api_keys_tenant_status ON api_keys (tenant_id, status);
CREATE INDEX idx_api_keys_client ON api_keys (client_id);

CREATE INDEX idx_master_upload_batches_list ON master_upload_batches (tenant_id, master_type, uploaded_at);
CREATE INDEX idx_master_upload_batches_status ON master_upload_batches (tenant_id, master_type, status);
CREATE INDEX idx_master_upload_batches_hash ON master_upload_batches (tenant_id, master_type, file_hash);
CREATE INDEX idx_product_master_items_name ON product_master_items (tenant_id, product_name);
CREATE INDEX idx_product_master_items_active ON product_master_items (tenant_id, active_yn);
CREATE INDEX idx_product_master_items_last_upload ON product_master_items (last_master_upload_batch_id);

CREATE INDEX idx_store_route_master_items_vehicle ON store_route_master_items (tenant_id, vehicle_name);
CREATE INDEX idx_store_route_master_items_area ON store_route_master_items (tenant_id, area);
CREATE INDEX idx_store_route_master_items_active ON store_route_master_items (tenant_id, active_yn);
CREATE INDEX idx_store_route_master_items_last_upload ON store_route_master_items (last_master_upload_batch_id);

CREATE INDEX idx_upload_batches_list ON upload_batches (tenant_id, client_id, delivery_date, status, uploaded_at);
CREATE INDEX idx_upload_batches_status ON upload_batches (tenant_id, client_id, status, confirmed_at);
CREATE INDEX idx_uploaded_files_batch ON uploaded_files (batch_id);
CREATE INDEX idx_uploaded_files_hash ON uploaded_files (file_hash);
CREATE INDEX idx_uploaded_files_name ON uploaded_files (tenant_id, client_id, original_file_name);
CREATE INDEX idx_excel_sheet_results_type ON excel_sheet_results (tenant_id, client_id, batch_id, sheet_type);

CREATE INDEX idx_scan_lines_batch ON scan_lines (tenant_id, client_id, batch_id);
CREATE INDEX idx_scan_lines_delivery_center ON scan_lines (tenant_id, client_id, delivery_date, scan_center);
CREATE INDEX idx_scan_lines_store ON scan_lines (tenant_id, client_id, order_business_site_code);
CREATE INDEX idx_scan_lines_product ON scan_lines (tenant_id, client_id, product_code);
CREATE INDEX idx_scan_lines_barcode ON scan_lines (tenant_id, client_id, barcode);

CREATE INDEX idx_pl_lines_batch ON pl_lines (tenant_id, client_id, batch_id);
CREATE INDEX idx_pl_lines_due_type ON pl_lines (tenant_id, client_id, due_date, pl_type);
CREATE INDEX idx_pl_lines_vehicle ON pl_lines (tenant_id, client_id, vehicle_name);
CREATE INDEX idx_pl_lines_store ON pl_lines (tenant_id, client_id, store_code);
CREATE INDEX idx_pl_lines_product ON pl_lines (tenant_id, client_id, product_code);
CREATE INDEX idx_pl_lines_order_no ON pl_lines (tenant_id, client_id, order_no);
CREATE INDEX idx_pl_lines_qr ON pl_lines (tenant_id, client_id, qr_code);

CREATE INDEX idx_label_lines_batch_type ON label_lines (tenant_id, client_id, batch_id, label_type);
CREATE INDEX idx_label_lines_store ON label_lines (tenant_id, client_id, store_code);
CREATE INDEX idx_label_lines_product ON label_lines (tenant_id, client_id, product_code);
CREATE INDEX idx_label_lines_matching ON label_lines (tenant_id, client_id, matching_code);
CREATE INDEX idx_label_lines_qr ON label_lines (tenant_id, client_id, qr_code);

CREATE INDEX idx_order_lines_batch ON order_lines (tenant_id, client_id, batch_id);
CREATE INDEX idx_order_lines_due ON order_lines (tenant_id, client_id, due_date);
CREATE INDEX idx_order_lines_store ON order_lines (tenant_id, client_id, store_code);
CREATE INDEX idx_order_lines_product ON order_lines (tenant_id, client_id, product_code);
CREATE INDEX idx_order_lines_vehicle ON order_lines (tenant_id, client_id, vehicle_name);

CREATE INDEX idx_validation_errors_batch ON validation_errors (batch_id);
CREATE INDEX idx_validation_errors_severity ON validation_errors (batch_id, severity);
CREATE INDEX idx_validation_errors_domain ON validation_errors (batch_id, domain);
CREATE INDEX idx_validation_errors_sheet_row ON validation_errors (batch_id, sheet_name, row_no);
CREATE INDEX idx_validation_errors_code ON validation_errors (batch_id, error_code);

CREATE INDEX idx_batch_audit_logs_batch ON batch_audit_logs (batch_id);
CREATE INDEX idx_batch_audit_logs_action ON batch_audit_logs (tenant_id, client_id, action);
CREATE INDEX idx_batch_audit_logs_created_at ON batch_audit_logs (tenant_id, client_id, created_at);
CREATE INDEX idx_batch_audit_logs_request_id ON batch_audit_logs (request_id);

CREATE INDEX idx_api_call_logs_api_key ON api_call_logs (api_key_id);
CREATE INDEX idx_api_call_logs_path ON api_call_logs (tenant_id, client_id, path);
CREATE INDEX idx_api_call_logs_created_at ON api_call_logs (tenant_id, client_id, created_at);
CREATE INDEX idx_api_call_logs_status ON api_call_logs (tenant_id, client_id, response_status);

CREATE INDEX idx_download_logs_batch ON download_logs (batch_id);
CREATE INDEX idx_download_logs_type ON download_logs (tenant_id, client_id, download_type);
CREATE INDEX idx_download_logs_user ON download_logs (downloaded_by);
CREATE INDEX idx_download_logs_downloaded_at ON download_logs (tenant_id, client_id, downloaded_at);
