package com.company.oms.common.error

enum class ErrorCode(
    val defaultMessage: String,
) {
    INVALID_REQUEST("요청 값이 올바르지 않습니다."),
    NOT_FOUND("요청한 리소스를 찾을 수 없습니다."),
    UNAUTHORIZED("인증이 필요합니다."),
    FORBIDDEN("권한이 없습니다."),
    INTERNAL_ERROR("서버 오류가 발생했습니다."),
    DUPLICATE_LOGIN_ID("이미 사용 중인 로그인 ID입니다."),
    INVALID_ROLE("존재하지 않는 역할입니다."),
    INVALID_USER_SCOPE("사용자 스코프와 tenant/client 값이 올바르지 않습니다."),
    USER_NOT_FOUND("사용자를 찾을 수 없습니다."),
    INVALID_API_KEY("API Key가 올바르지 않습니다."),
    API_KEY_NOT_FOUND("API Key를 찾을 수 없습니다."),
    INVALID_SCOPE("API Key scope가 올바르지 않습니다."),
    INVALID_EXPIRES_AT("API Key 만료 시각이 올바르지 않습니다."),
    VALIDATION_FAILED("검증 오류가 존재합니다."),
    FILE_UPLOAD_FAILED("파일 업로드에 실패했습니다."),
    FILE_TOO_LARGE("업로드 파일 크기가 허용 범위를 초과했습니다."),
    INVALID_FILE_EXTENSION("허용되지 않는 파일 확장자입니다."),
    INVALID_COLUMNS("필수 컬럼이 누락되었습니다."),
    SHEET_NOT_FOUND("대상 시트를 찾을 수 없습니다."),
    DUPLICATE_MASTER_KEY("마스터 파일 안에 중복 키가 존재합니다."),
    BATCH_NOT_FOUND("배치를 찾을 수 없습니다."),
    BATCH_NOT_CONFIRMED("확정된 배치만 조회 또는 다운로드할 수 있습니다."),
    NO_CONFIRMED_BATCH("조건에 맞는 확정 배치를 찾을 수 없습니다."),
    NO_DATA("조건에 맞는 데이터가 없습니다."),
    ORDER_LINE_NOT_FOUND("주문 조회용 행을 찾을 수 없습니다."),
    LABEL_LINE_NOT_FOUND("라벨 행을 찾을 수 없습니다."),
    DOWNLOAD_LOG_NOT_FOUND("다운로드 이력을 찾을 수 없습니다."),
    INVALID_BATCH_STATUS("현재 배치 상태에서는 수행할 수 없습니다."),
    VALIDATION_ERROR_EXISTS("Error 등급 검증 오류가 존재합니다."),
    CLIENT_NOT_FOUND("고객사 또는 화주사를 찾을 수 없습니다."),
    MASTER_VERSION_NOT_FOUND("마스터 버전을 찾을 수 없습니다."),
}
