export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  clients: {
    list: '/clients',
    resolveCandidates: '/clients/resolve-candidates',
    detail: (clientId: number) => `/clients/${clientId}`,
  },
  tenants: {
    list: '/tenants',
    detail: (tenantId: number) => `/tenants/${tenantId}`,
  },
  apiKeys: {
    list: '/api-keys',
    detail: (apiKeyId: number) => `/api-keys/${apiKeyId}`,
    revoke: (apiKeyId: number) => `/api-keys/${apiKeyId}/revoke`,
  },
  batches: {
    list: '/order-excel-batches',
    detail: (batchId: number) => `/order-excel-batches/${batchId}`,
    validate: (batchId: number) => `/order-excel-batches/${batchId}/validate`,
    requestConfirmation: (batchId: number) => `/order-excel-batches/${batchId}/confirmation-requests`,
    confirm: (batchId: number) => `/order-excel-batches/${batchId}/confirm`,
    cancel: (batchId: number) => `/order-excel-batches/${batchId}/cancel`,
    rollback: (batchId: number) => `/order-excel-batches/${batchId}/rollback`,
    validationErrors: (batchId: number) => `/order-excel-batches/${batchId}/validation-errors`,
  },
  batchConfirmationRequests: {
    list: '/batch-confirmation-requests',
    detail: (requestId: number) => `/batch-confirmation-requests/${requestId}`,
    approve: (requestId: number) => `/batch-confirmation-requests/${requestId}/approve`,
    reject: (requestId: number) => `/batch-confirmation-requests/${requestId}/reject`,
    needsMoreInfo: (requestId: number) => `/batch-confirmation-requests/${requestId}/needs-more-info`,
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (notificationId: number) => `/notifications/${notificationId}/read`,
    markAllRead: '/notifications/read-all',
  },
  workItems: {
    summary: '/work-items/summary',
  },
  orders: '/orders',
  scanLines: '/scan-lines',
  plLines: '/pl-lines',
  labelLines: '/label-lines',
  labelDownloads: '/downloads/labels',
  externalApi: {
    status: '/external-api/status',
  },
  masters: {
    products: '/masters/products',
    productUploads: '/masters/products/uploads',
    productUploadPreview: '/masters/products/uploads/preview',
    productUploadApply: (uploadId: number | string) => `/masters/products/uploads/${uploadId}/apply`,
    productUploadCancel: (uploadId: number | string) => `/masters/products/uploads/${uploadId}/cancel`,
    productUploadRowErrors: (uploadId: number | string) => `/masters/products/uploads/${uploadId}/row-errors`,
    storeRoutes: '/masters/store-routes',
    storeRouteUploads: '/masters/store-routes/uploads',
    storeRouteUploadPreview: '/masters/store-routes/uploads/preview',
    storeRouteUploadApply: (uploadId: number | string) => `/masters/store-routes/uploads/${uploadId}/apply`,
    storeRouteUploadCancel: (uploadId: number | string) => `/masters/store-routes/uploads/${uploadId}/cancel`,
    storeRouteUploadRowErrors: (uploadId: number | string) => `/masters/store-routes/uploads/${uploadId}/row-errors`,
    clientProductCodeMappings: '/masters/client-product-code-mappings',
    clientStoreCodeMappings: '/masters/client-store-code-mappings',
  },
  clientMasterVisibility: {
    settings: '/client-master-visibility/settings',
    productScopes: '/client-master-visibility/product-scopes',
    storeRouteScopes: '/client-master-visibility/store-route-scopes',
  },
  clientMasters: {
    products: '/client-masters/products',
    storeRoutes: '/client-masters/store-routes',
  },
  audit: {
    batches: '/audit/batches',
    apiCalls: '/audit/api-calls',
    downloads: '/audit/downloads',
  },
} as const;
